# Generated by Django 5.1.6 on 2025-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='transcription_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
