# Generated by Django 5.1.6 on 2025-03-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedimage_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
