# Generated by Django 5.1.6 on 2025-03-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_uploadedimage_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_text",
                        to="api.uploadedimage",
                    ),
                ),
            ],
        ),
    ]
