# Generated by Django 5.1.6 on 2025-03-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_extractedtext"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractedtext",
            old_name="extracted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="transcription_data",
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_text",
                to="api.uploadedimage",
            ),
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="text",
            field=models.TextField(),
        ),
    ]
