# Generated by Django 5.1.6 on 2025-03-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_extracted_at_extractedtext_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractedtext",
            old_name="created_at",
            new_name="extracted_at",
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_text",
                to="api.uploadedimage",
            ),
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
