# Generated by Django 5.1.6 on 2025-04-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_created_at_extractedtext_extracted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="language",
            field=models.CharField(
                choices=[("english", "English"), ("nepali", "Nepali")],
                default="english",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("ocr_failed", "OCR Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
